--vim.opt.laststatus = 2
---- Based on https://github.com/maxverbeek/nixconfig/blob/master/home/modules/nvim/config/lua/maxconf/lualine.lua
--require('lualine').setup {
  --options = {
    --icons_enabled = true,
    --theme = 'nord',
    --component_separators = { left = '', right = ''},
    --section_separators = { left = '', right = ''},
    --disabled_filetypes = {},
    --always_divide_middle = true,
  --},
  --sections = {
    --lualine_a = {'mode'},
    --lualine_b = {'diff', 'diagnostics'},
    --lualine_c = {'filename'},
    --lualine_x = {'encoding', 'fileformat', 'filetype'},
    --lualine_y = {'location'},
    --lualine_z = {'branch'}
  --},
  --inactive_sections = {
    --lualine_a = {},
    --lualine_b = {},
    --lualine_c = {'filename'},
    --lualine_x = {'location'},
    --lualine_y = {},
    --lualine_z = {}
  --},
  --tabline = {},
  --extensions = {}
--}
