name: 113
root: ~/Workspace/researchable/projects/113-suicide-prevention

windows:
  - serverless:
      layout: add3,239x62,0,0[239x17,0,0{117x17,0,0,13,121x17,118,0,15},239x44,0,18,14]
      panes:
      - azure-serverless:
        - cd base-backend/mail-catcher
        - yarn start
      - tsc:
        - cd base-backend/mail-catcher
        - yarn watch
      - editor:
        - cd base-backend/mail-catcher
        - nvim
  - development:
      layout: 7adc,213x62,0,0[213x12,0,0{78x12,0,0[78x6,0,0,0,78x5,0,7,4],68x12,79,0,1,65x12,148,0,2},213x49,0,13,3]
      panes:
      - fe:
        - cd base-frontend
        - yarn run dev
      - storybook:
        - cd base-frontend
        - yarn storybook --ci
      - be:
        - cd base-backend
        - dcbu
      - auth:
        - cd svc-auth
        #- dcbu
      - vim:
        - cd base-frontend
        - nvim

