name: cia
root: ~/Workspace/researchable/projects/cia/composer

windows:
  - development:
      layout: 9424,208x59,0,0[208x10,0,0{77x10,0,0,0,63x10,78,0,1,66x10,142,0,4},208x48,0,11,2]
      panes:
      - app-one:
        - cd base-frontend
        - yarn run dev
      - app-two:
        - cd base-backend
        - dcbu
      - app-two:
        - cd svc-auth
        - dcbu
      - app-three:
        - cd base-frontend
        - nvim

