name: sdv
root: ~/Workspace/researchable/sport-data-valley/MVP/

windows:
  - development:
      layout: 7adc,213x62,0,0[213x12,0,0{78x12,0,0[78x6,0,0,0,78x5,0,7,4],68x12,79,0,1,65x12,148,0,2},213x49,0,13,3]
      panes:
      - be:
        - cd base-platform
        - docker compose -f docker-compose.single.yml up --build
      - storybook:
        - cd base-frontend
        - yarn storybook --ci
      - be:
        - cd base-backend
      - auth:
        - cd svc-auth
      - vim:
        - cd base-platform
        - nvim
